apiVersion: v1
kind: Namespace
metadata:
  name: dashboard
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dashboard
  name: dashboard-deployment
  labels:
    app: dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: pramodepandit/dashboard:master
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: dashboard-service
  namespace: dashboard
spec:
  selector:
    app: dashboard
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: dashboard
spec:
  rules:
  - host: dashboard.cmaclustermiapps.us-south.containers.appdomain.cloud
    http:
      paths:
      - backend:
          serviceName: dashboard-service
          servicePort: 80
